apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-project-deployment
  labels:
    app: k8s-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-project
  template:
    metadata:
      labels:
        app: k8s-project
    spec:
      containers:
        - name: k8s-project-container
          image: k8s-project:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "development"
          volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes:
        - name: app-volume
          hostPath:
            path: /path/to/your/local/directory
            type: Directory
